- name: Konsave
  hosts: localhost
  vars:
    - env_shell: "{{ lookup('env', 'SHELL') }}"
    - packages: {
           ArchLinux: [python-pipx, python-setuptools],
           Debian: [python-pipx, python-setuptools],
           RedHat: [pipx, python-setuptools]
      }
  tasks:
    - name: (debug) Show OS Family
      debug:
        msg: "OS Family is {{ ansible_os_family }}, package manager - {{ ansible_pkg_mgr }}"
    - name: Install pipx
      become: true
      ansible.builtin.package:
        name: "{{ packages[ansible_os_family] }}"
        state: present

    - name: Install konsave
      community.general.pipx:
        name: konsave
        state: present
    
    - name: Install setuptools for konsave
      ansible.builtin.command:
        cmd: pipx runpip konsave install setuptools

    - name: Set up competitions (BASH)
      ansible.builtin.lineinfile:
        dest: ~/.bashrc
        line: "eval \"$(register-python-argcomplete pipx)\""
      when: '"bash" in env_shell'

    - name: Set up competitions (ZSH)
      ansible.builtin.lineinfile:
        dest: ~/.bashrc
        line: "eval \"$(register-python-argcomplete pipx)\""
      when: '"zsh" in env_shell'

    - name: Copy konsave profile
      ansible.builtin.copy:
        src: ./konsave
        dest: ~/.config/
        mode: '0700'

    - name: Apply konsave
      ansible.builtin.command:
        cmd: konsave -a leito
