- name: Dotfiles
  hosts: all
  vars:
    dotfiles_path: ~/.dotfiles/config
    configs:
      - { src: "{{ dotfiles_path }}/starship.toml", dest: "~/.config/starship.toml" }
      - { src: "{{ dotfiles_path }}/.antigenrc", dest: "~/.config/.antigenrc" }
      - { src: "{{ dotfiles_path }}/.zshrc", dest: "~/.zshrc"}
  tasks:
    - name: Install zsh
      become: "{{ 'false' if ansible_facts['os_family'] == 'Darwin' else 'true' }}"
      ansible.builtin.package:
        name:
          # - ttf-hack-nerd
          - zsh
          - git
          - vim
    - name: Create .config folder
      ansible.builtin.file:
        state: directory
        mode: '0770'
        path: ~/.config/

    - name: Clone dotfiles
      ansible.builtin.git:
        repo: https://github.com/leitosama/dotfiles.git
        dest: ~/.dotfiles/
        version: dev
        single_branch: true

    - name: Fetch starship
      ansible.builtin.uri:
        url: https://starship.rs/install.sh
        return_content: true
      register: starship_installer

    - name: Run starship installer
      become: true
      ansible.builtin.command:
        cmd: "sh -s -- -y"
        stdin: "{{ starship_installer.content }}"
        creates: /usr/local/bin/starship

    - name: Get the username running the deploy
      become: false
      changed_when: false
      ansible.builtin.command: whoami
      register: whoami

    - name: Change default shell
      become: true
      ansible.builtin.user:
        name: "{{ whoami.stdout }}"
        shell: "/bin/zsh"
        state: present

    - name: Install antigen
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/zsh-users/antigen/8846aa9/bin/antigen.zsh
        dest: ~/.antigen.zsh
        mode: '0660'

    - name: Delete old files
      ansible.builtin.file:
        path: "{{ item.dest }}"
        state: absent
      loop: "{{ configs }}"

    - name: Link configs to paths
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0600'
        state: link
      loop: "{{ configs }}"
