# Theme: Aura
# Palette of Aura Theme by Dalton Menezes (https://github.com/daltonmenezes/aura-theme)

# Main bg
theme[main_bg]="#15141b"

# Main text color
theme[main_fg]="#edecee"

# Title color for boxes
theme[title]="#edecee"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#a277ff"

# Background color of selected item in processes box
theme[selected_bg]="#29263c"

# Foreground color of selected item in processes box
theme[selected_fg]="#edecee"

# Color of inactive/disabled text
theme[inactive_fg]="#6d6d6d"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a277ff"

# Box outline colors
theme[cpu_box]="#3d375e"
theme[mem_box]="#3d375e"
theme[net_box]="#3d375e"
theme[proc_box]="#3d375e"

# Box divider line and small boxes line color
theme[div_line]="#3d375e"

# Temperature graph colors
theme[temp_start]="#61ffca"
theme[temp_mid]="#ffca85"
theme[temp_end]="#ff6767"

# CPU graph colors
theme[cpu_start]="#61ffca"
theme[cpu_mid]="#ffca85"
theme[cpu_end]="#ff6767"

# Mem/Disk free meter
theme[free_start]="#61ffca"
theme[free_mid]="#a277ff"
theme[free_end]="#f694ff"

# Mem/Disk cached meter
theme[cached_start]="#61ffca"
theme[cached_mid]="#a277ff"
theme[cached_end]="#f694ff"

# Mem/Disk available meter
theme[available_start]="#61ffca"
theme[available_mid]="#ffca85"
theme[available_end]="#ff6767"

# Mem/Disk used meter
theme[used_start]="#61ffca"
theme[used_mid]="#ffca85"
theme[used_end]="#ff6767"

# Download graph colors
theme[download_start]="#61ffca"
theme[download_mid]="#a277ff"
theme[download_end]="#f694ff"

# Upload graph colors
theme[upload_start]="#61ffca"
theme[upload_mid]="#ffca85"
theme[upload_end]="#ff6767"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#61ffca"
theme[process_mid]="#a277ff"
theme[process_end]="#f694ff"
